apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::233751584262:user/harkesh
      username: harkesh
      groups:
        - system:masters

    - userarn: arn:aws:iam::233751584262:user/gaurav
      username: gaurav
      groups:
        - system:masters
