apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-1
spec:
  replicas: 3
  selector:
    app: kubia-1
  template:
    metadata:
      labels:
        app: kubia-1
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080