apiVersion: v1
kind: ReplicaSet
metadata:
  name: kubia
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubia
      Role: webserver
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080