apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  namespace: dev
spec:
  replicas: 2
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: harkeshkumar/kubernetes-course:nginx-hostname-v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80